CREATE TABLE hotel_db.Restaurant (
	
    RESTAURANT_ID int(11) NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL,
    RESTAURANTNAME VARCHAR(45) NOT NULL,
    ADDRESS VARCHAR(50)  NOT NULL,
    CITY VARCHAR(45) NOT NULL,
    ZIP INT(11) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    OPERATINGDAYS VARCHAR(100) NOT NULL,
    OPENINGTIME time NOT NULL,
    CLOSINGTIME time NOT NULL,
    AUTOASSIGN BOOLEAN default TRUE,
    PRIMARY KEY (RESTAURANT_ID)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;



INSERT INTO hotel_db.Restaurant (EMAIL, RESTAURANTNAME, ADDRESS, CITY, ZIP, PHONE, STATE, OPERATINGDAYS, OPENINGTIME, CLOSINGTIME) VALUES 
('info@indiaspice.com', 'INDIAN SPICE','28 MySQL Boulevard','Palo Alto',94301,'2830338429', 'California', 'Mon Tue Wed Thurs Fri Sat Sun','9:00','22:00');


CREATE TABLE RestaurantTables (
  RESTAURANTID int(11) NOT NULL,
  TABLENO int(11) NOT NULL,
  CAPACITY int(11) NOT NULL,
  AVAILABILITY BOOLEAN DEFAULT TRUE,
  Key(TABLENO),
  Key(RESTAURANTID),
  PRIMARY KEY (RESTAURANTID, TABLENO),
  foreign key(RESTAURANTID) references Restaurant(RESTAURANT_ID)
 ) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

INSERT INTO hotel_db.RestaurantTables (RESTAURANTID, TABLENO,CAPACITY) VALUES
('1','1','5'),('1','2','2'),('1','3','6'),('1','4','8'),('1','5','4'),('1','6','4'),('1','7','4'); 


CREATE TABLE hotel_db.Reservations (
	
    RESERVATION_ID int(11) NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL,
    CUSTOMER_NAME VARCHAR(45) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    RESERVATION_DATE date NOT NULL,
    RESERVATION_TIME time NOT NULL,
	PARTY_SIZE int(11) NOT NULL,
    RESERVATION_TABLE_NO int(11) NOT NULL,
    RESERVATION_RESTAURANT_ID int(11) NOT NULL,
    RESERVATION_STATUS VARCHAR(10) NOT NULL,
    PRIMARY KEY (RESERVATION_ID),
    foreign key (RESERVATION_TABLE_NO) references RestaurantTables(TABLENO),
    foreign key (RESERVATION_RESTAURANT_ID) references RestaurantTables(RESTAURANTID)
)ENGINE=INNODB AUTO_INCREMENT= 1000 DEFAULT CHARSET=UTF8;

INSERT INTO hotel_db.Reservations (EMAIL, CUSTOMER_NAME, PHONE, RESERVATION_DATE, RESERVATION_TIME, PARTY_SIZE, RESERVATION_TABLE_NO, RESERVATION_RESTAURANT_ID,RESERVATION_STATUS ) VALUES 
('karthikbangera@test.com', 'KB', '2830338429', '2015-11-24', '10:00','5','1','1','Confirmed'); 

CREATE TABLE hotel_db.Administrator (
EMAIL VARCHAR(45) NOT NULL,
PASSOWRD VARCHAR(10) NOT NULL,
ADMIN_NAME VARCHAR(45) NOT NULL,
PHONE VARCHAR(10) NOT NULL,
RESTAURANT_ID int(11) NOT NULL,
TOKEN int(11) NULL,
PRIMARY KEY (EMAIL)
)ENGINE=INNODB AUTO_INCREMENT= 1000 DEFAULT CHARSET=UTF8;

INSERT INTO hotel_db.Administrator(EMAIL,PASSOWRD,ADMIN_NAME,PHONE,RESTAURANT_ID) VALUES 
('adminkarthik@infospice.com','test123','Karthik', '3451235678',1);
